###########################################
# MTES Application Stack Configuration
# Docker Compose for Deployment
###########################################

services:
  #-----------------------------------------
  # Backend Service
  #-----------------------------------------
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: mtes-backend
    ports:
      - '3333:3333'
    env_file:
      - apps/backend/.env.production
    networks:
      - app-network
    restart: unless-stopped

  #-----------------------------------------
  # Frontend Service
  #-----------------------------------------
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: mtes-frontend
    ports:
      - '4200:4200'
    env_file:
      - apps/frontend/.env.production
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped


#-----------------------------------------
# Networks
#-----------------------------------------
networks:
  app-network:
    driver: bridge
