version: '3.8'

services:
  mongodb:
    image: mongo:7.0.5
    container_name: mtes-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
      - ./data:/data/backup
    networks:
      - mtes-network
    restart: always

  backend:
    build:
      dockerfile: apps/backend/Dockerfile
      context: .
    environment:
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      HOST: 0.0.0.0
      PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - mongodb
    networks:
      - mtes-network
    restart: always

  frontend:
    build:
      dockerfile: apps/frontend/Dockerfile
      context: .
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
      NEXT_INTERNAL_API_URL: ${NEXT_INTERNAL_API_URL}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    networks:
      - mtes-network
    restart: always

volumes:
  mongodb_data:
    driver: local

networks:
  mtes-network:
    driver: bridge
