services:
  backend:
    build:
      dockerfile: apps/backend/Dockerfile
      context: .
    env_file:
      - './apps/backend/.env.prod'
    ports:
      - '3333:3333'
    networks:
      - mtes-network
    restart: always

  frontend:
    build:
      dockerfile: apps/frontend/Dockerfile
      context: .
    env_file:
      - './apps/frontend/.env.prod'
    ports:
      - '4200:4200'
    depends_on:
      - backend
    networks:
      - mtes-network
    restart: always

networks:
  mtes-network:
    driver: bridge
